var wms_layers = [];


        var lyr_GoogleSatellite_0 = new ol.layer.Tile({
            'title': 'Google Satellite',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' &middot; <a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>',
                url: 'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}'
            })
        });
var format_LimitiProvinciali_1 = new ol.format.GeoJSON();
var features_LimitiProvinciali_1 = format_LimitiProvinciali_1.readFeatures(json_LimitiProvinciali_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_LimitiProvinciali_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_LimitiProvinciali_1.addFeatures(features_LimitiProvinciali_1);
var lyr_LimitiProvinciali_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_LimitiProvinciali_1, 
                style: style_LimitiProvinciali_1,
                interactive: false,
                title: '<img src="styles/legend/LimitiProvinciali_1.png" /> Limiti Provinciali '
            });
var format_Limiticomunali_2 = new ol.format.GeoJSON();
var features_Limiticomunali_2 = format_Limiticomunali_2.readFeatures(json_Limiticomunali_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Limiticomunali_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Limiticomunali_2.addFeatures(features_Limiticomunali_2);
var lyr_Limiticomunali_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Limiticomunali_2, 
                style: style_Limiticomunali_2,
                interactive: false,
                title: '<img src="styles/legend/Limiticomunali_2.png" /> Limiti comunali'
            });
var format_Province_EmissioniCO2_3 = new ol.format.GeoJSON();
var features_Province_EmissioniCO2_3 = format_Province_EmissioniCO2_3.readFeatures(json_Province_EmissioniCO2_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Province_EmissioniCO2_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Province_EmissioniCO2_3.addFeatures(features_Province_EmissioniCO2_3);
var lyr_Province_EmissioniCO2_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Province_EmissioniCO2_3, 
                style: style_Province_EmissioniCO2_3,
                interactive: false,
    title: 'Province_Emissioni CO2<br />\
    <img src="styles/legend/Province_EmissioniCO2_3_0.png" /> 12,48<br />\
    <img src="styles/legend/Province_EmissioniCO2_3_1.png" /> 105,04<br />\
    <img src="styles/legend/Province_EmissioniCO2_3_2.png" /> 149,03<br />\
    <img src="styles/legend/Province_EmissioniCO2_3_3.png" /> 178,10<br />\
    <img src="styles/legend/Province_EmissioniCO2_3_4.png" /> 216,13<br />\
    <img src="styles/legend/Province_EmissioniCO2_3_5.png" /> 4200,63<br />'
        });
var format_Province_ClasseenergeticaA4nzeb_4 = new ol.format.GeoJSON();
var features_Province_ClasseenergeticaA4nzeb_4 = format_Province_ClasseenergeticaA4nzeb_4.readFeatures(json_Province_ClasseenergeticaA4nzeb_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Province_ClasseenergeticaA4nzeb_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Province_ClasseenergeticaA4nzeb_4.addFeatures(features_Province_ClasseenergeticaA4nzeb_4);
var lyr_Province_ClasseenergeticaA4nzeb_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Province_ClasseenergeticaA4nzeb_4, 
                style: style_Province_ClasseenergeticaA4nzeb_4,
                interactive: false,
    title: 'Province_Classe energetica A4 nzeb<br />\
    <img src="styles/legend/Province_ClasseenergeticaA4nzeb_4_0.png" /> 0<br />\
    <img src="styles/legend/Province_ClasseenergeticaA4nzeb_4_1.png" /> 1<br />\
    <img src="styles/legend/Province_ClasseenergeticaA4nzeb_4_2.png" /> 3<br />\
    <img src="styles/legend/Province_ClasseenergeticaA4nzeb_4_3.png" /> 38<br />'
        });
var format_Province_PunteggioITACA_5 = new ol.format.GeoJSON();
var features_Province_PunteggioITACA_5 = format_Province_PunteggioITACA_5.readFeatures(json_Province_PunteggioITACA_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Province_PunteggioITACA_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Province_PunteggioITACA_5.addFeatures(features_Province_PunteggioITACA_5);
var lyr_Province_PunteggioITACA_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Province_PunteggioITACA_5, 
                style: style_Province_PunteggioITACA_5,
                interactive: false,
    title: 'Province_Punteggio ITACA<br />\
    <img src="styles/legend/Province_PunteggioITACA_5_0.png" /> 2,25<br />\
    <img src="styles/legend/Province_PunteggioITACA_5_1.png" /> 2,36<br />\
    <img src="styles/legend/Province_PunteggioITACA_5_2.png" /> 2,40<br />\
    <img src="styles/legend/Province_PunteggioITACA_5_3.png" /> 2,76<br />\
    <img src="styles/legend/Province_PunteggioITACA_5_4.png" /> 2,83<br />\
    <img src="styles/legend/Province_PunteggioITACA_5_5.png" /> 3,35<br />'
        });
var format_Province_VolumeincentivodecretoRomanimc_6 = new ol.format.GeoJSON();
var features_Province_VolumeincentivodecretoRomanimc_6 = format_Province_VolumeincentivodecretoRomanimc_6.readFeatures(json_Province_VolumeincentivodecretoRomanimc_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Province_VolumeincentivodecretoRomanimc_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Province_VolumeincentivodecretoRomanimc_6.addFeatures(features_Province_VolumeincentivodecretoRomanimc_6);
var lyr_Province_VolumeincentivodecretoRomanimc_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Province_VolumeincentivodecretoRomanimc_6, 
                style: style_Province_VolumeincentivodecretoRomanimc_6,
                interactive: false,
    title: 'Province_Volume incentivo decreto Romani mc<br />\
    <img src="styles/legend/Province_VolumeincentivodecretoRomanimc_6_0.png" /> 0<br />\
    <img src="styles/legend/Province_VolumeincentivodecretoRomanimc_6_1.png" /> 106<br />\
    <img src="styles/legend/Province_VolumeincentivodecretoRomanimc_6_2.png" /> 152<br />\
    <img src="styles/legend/Province_VolumeincentivodecretoRomanimc_6_3.png" /> 240<br />\
    <img src="styles/legend/Province_VolumeincentivodecretoRomanimc_6_4.png" /> 9462<br />'
        });
var format_Province_VolumeincentivoLR142009mc_7 = new ol.format.GeoJSON();
var features_Province_VolumeincentivoLR142009mc_7 = format_Province_VolumeincentivoLR142009mc_7.readFeatures(json_Province_VolumeincentivoLR142009mc_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Province_VolumeincentivoLR142009mc_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Province_VolumeincentivoLR142009mc_7.addFeatures(features_Province_VolumeincentivoLR142009mc_7);
var lyr_Province_VolumeincentivoLR142009mc_7 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Province_VolumeincentivoLR142009mc_7, 
                style: style_Province_VolumeincentivoLR142009mc_7,
                interactive: false,
    title: 'Province_Volume incentivo LR 14/2009 mc<br />\
    <img src="styles/legend/Province_VolumeincentivoLR142009mc_7_0.png" /> 0<br />\
    <img src="styles/legend/Province_VolumeincentivoLR142009mc_7_1.png" /> 101<br />\
    <img src="styles/legend/Province_VolumeincentivoLR142009mc_7_2.png" /> 2013<br />\
    <img src="styles/legend/Province_VolumeincentivoLR142009mc_7_3.png" /> 2378<br />\
    <img src="styles/legend/Province_VolumeincentivoLR142009mc_7_4.png" /> 8232<br />\
    <img src="styles/legend/Province_VolumeincentivoLR142009mc_7_5.png" /> 74323<br />'
        });
var format_Province_VolumeincentivoLR132008mc_8 = new ol.format.GeoJSON();
var features_Province_VolumeincentivoLR132008mc_8 = format_Province_VolumeincentivoLR132008mc_8.readFeatures(json_Province_VolumeincentivoLR132008mc_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Province_VolumeincentivoLR132008mc_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Province_VolumeincentivoLR132008mc_8.addFeatures(features_Province_VolumeincentivoLR132008mc_8);
var lyr_Province_VolumeincentivoLR132008mc_8 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Province_VolumeincentivoLR132008mc_8, 
                style: style_Province_VolumeincentivoLR132008mc_8,
                interactive: false,
    title: 'Province_Volume incentivo LR 13/2008 mc<br />\
    <img src="styles/legend/Province_VolumeincentivoLR132008mc_8_0.png" /> 0<br />\
    <img src="styles/legend/Province_VolumeincentivoLR132008mc_8_1.png" /> 152<br />\
    <img src="styles/legend/Province_VolumeincentivoLR132008mc_8_2.png" /> 272<br />\
    <img src="styles/legend/Province_VolumeincentivoLR132008mc_8_3.png" /> 340<br />\
    <img src="styles/legend/Province_VolumeincentivoLR132008mc_8_4.png" /> 2535<br />\
    <img src="styles/legend/Province_VolumeincentivoLR132008mc_8_5.png" /> 15815<br />'
        });
var format_Numerocertificazioniperprovincia_9 = new ol.format.GeoJSON();
var features_Numerocertificazioniperprovincia_9 = format_Numerocertificazioniperprovincia_9.readFeatures(json_Numerocertificazioniperprovincia_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Numerocertificazioniperprovincia_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Numerocertificazioniperprovincia_9.addFeatures(features_Numerocertificazioniperprovincia_9);
var lyr_Numerocertificazioniperprovincia_9 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Numerocertificazioniperprovincia_9, 
                style: style_Numerocertificazioniperprovincia_9,
                interactive: false,
    title: 'Numero certificazioni per provincia<br />\
    <img src="styles/legend/Numerocertificazioniperprovincia_9_0.png" /> 3<br />\
    <img src="styles/legend/Numerocertificazioniperprovincia_9_1.png" /> 7<br />\
    <img src="styles/legend/Numerocertificazioniperprovincia_9_2.png" /> 10<br />\
    <img src="styles/legend/Numerocertificazioniperprovincia_9_3.png" /> 12<br />\
    <img src="styles/legend/Numerocertificazioniperprovincia_9_4.png" /> 34<br />\
    <img src="styles/legend/Numerocertificazioniperprovincia_9_5.png" /> 179<br />'
        });
var format_Certificatidisostenibilit2022punteggioItaca_10 = new ol.format.GeoJSON();
var features_Certificatidisostenibilit2022punteggioItaca_10 = format_Certificatidisostenibilit2022punteggioItaca_10.readFeatures(json_Certificatidisostenibilit2022punteggioItaca_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Certificatidisostenibilit2022punteggioItaca_10 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Certificatidisostenibilit2022punteggioItaca_10.addFeatures(features_Certificatidisostenibilit2022punteggioItaca_10);
var lyr_Certificatidisostenibilit2022punteggioItaca_10 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Certificatidisostenibilit2022punteggioItaca_10, 
                style: style_Certificatidisostenibilit2022punteggioItaca_10,
                interactive: false,
    title: 'Certificati di sostenibilità 2022 punteggio Itaca<br />\
    <img src="styles/legend/Certificatidisostenibilit2022punteggioItaca_10_0.png" /> 1 - 2<br />\
    <img src="styles/legend/Certificatidisostenibilit2022punteggioItaca_10_1.png" /> 2 - 3<br />\
    <img src="styles/legend/Certificatidisostenibilit2022punteggioItaca_10_2.png" /> 3 - 4<br />\
    <img src="styles/legend/Certificatidisostenibilit2022punteggioItaca_10_3.png" /> 4 - 5<br />'
        });
var format_Certificatidisostenibilit2022_11 = new ol.format.GeoJSON();
var features_Certificatidisostenibilit2022_11 = format_Certificatidisostenibilit2022_11.readFeatures(json_Certificatidisostenibilit2022_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Certificatidisostenibilit2022_11 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Certificatidisostenibilit2022_11.addFeatures(features_Certificatidisostenibilit2022_11);
var lyr_Certificatidisostenibilit2022_11 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Certificatidisostenibilit2022_11, 
                style: style_Certificatidisostenibilit2022_11,
                interactive: false,
    title: 'Certificati di sostenibilità 2022<br />\
    <img src="styles/legend/Certificatidisostenibilit2022_11_0.png" /> BA<br />\
    <img src="styles/legend/Certificatidisostenibilit2022_11_1.png" /> BR<br />\
    <img src="styles/legend/Certificatidisostenibilit2022_11_2.png" /> BT<br />\
    <img src="styles/legend/Certificatidisostenibilit2022_11_3.png" /> FG<br />\
    <img src="styles/legend/Certificatidisostenibilit2022_11_4.png" /> LE<br />\
    <img src="styles/legend/Certificatidisostenibilit2022_11_5.png" /> TA<br />'
        });

lyr_GoogleSatellite_0.setVisible(true);lyr_LimitiProvinciali_1.setVisible(true);lyr_Limiticomunali_2.setVisible(true);lyr_Province_EmissioniCO2_3.setVisible(true);lyr_Province_ClasseenergeticaA4nzeb_4.setVisible(true);lyr_Province_PunteggioITACA_5.setVisible(true);lyr_Province_VolumeincentivodecretoRomanimc_6.setVisible(true);lyr_Province_VolumeincentivoLR142009mc_7.setVisible(true);lyr_Province_VolumeincentivoLR132008mc_8.setVisible(true);lyr_Numerocertificazioniperprovincia_9.setVisible(true);lyr_Certificatidisostenibilit2022punteggioItaca_10.setVisible(true);lyr_Certificatidisostenibilit2022_11.setVisible(true);
var layersList = [lyr_GoogleSatellite_0,lyr_LimitiProvinciali_1,lyr_Limiticomunali_2,lyr_Province_EmissioniCO2_3,lyr_Province_ClasseenergeticaA4nzeb_4,lyr_Province_PunteggioITACA_5,lyr_Province_VolumeincentivodecretoRomanimc_6,lyr_Province_VolumeincentivoLR142009mc_7,lyr_Province_VolumeincentivoLR132008mc_8,lyr_Numerocertificazioniperprovincia_9,lyr_Certificatidisostenibilit2022punteggioItaca_10,lyr_Certificatidisostenibilit2022_11];
lyr_LimitiProvinciali_1.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', });
lyr_Limiticomunali_2.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ID': 'ID', 'AREA_': 'AREA_', 'PERIMETER': 'PERIMETER', 'COMUNI_': 'COMUNI_', 'COMUNI_ID': 'COMUNI_ID', 'COD_ISTAT': 'COD_ISTAT', 'NOME_COM': 'NOME_COM', 'ISTAT': 'ISTAT', 'COD_REG': 'COD_REG', 'COD_PRO': 'COD_PRO', 'COD_COM': 'COD_COM', 'NEWFIELD1': 'NEWFIELD1', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', });
lyr_Province_EmissioniCO2_3.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Province_Conteggio certificazioni': 'Province_Conteggio certificazioni', 'Province_Volume incentivo LR 13/2008 mc': 'Province_Volume incentivo LR 13/2008 mc', 'Province_Volume incentivo LR 14/2009 mc': 'Province_Volume incentivo LR 14/2009 mc', 'Province_Volume incentivo decreto Romani mc': 'Province_Volume incentivo decreto Romani mc', 'Province_Punteggio ITACA': 'Province_Punteggio ITACA', 'Province_Classe energetica A4 nzeb': 'Province_Classe energetica A4 nzeb', 'Province_Classe energetica A4': 'Province_Classe energetica A4', 'Province_Classe energetica A3': 'Province_Classe energetica A3', 'Province_Classe energetica A2': 'Province_Classe energetica A2', 'Province_Classe energetica A1': 'Province_Classe energetica A1', 'Province_Classe energetica B': 'Province_Classe energetica B', 'Province_Classe energetica C': 'Province_Classe energetica C', 'Province_Classe energetica D': 'Province_Classe energetica D', 'Province_Emissioni CO2': 'Province_Emissioni CO2', 'Province_CO2 x SU': 'Province_CO2 x SU', 'Province_Impianto FV KW': 'Province_Impianto FV KW', 'Province_% copertura consumi ACS': 'Province_% copertura consumi ACS', 'Province_% consumi ACS, risc, raffr': 'Province_% consumi ACS, risc, raffr', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Province_Indicatore prestazione criterio C.4.3 (%)', 'Province_Aree sistemate a verde': 'Province_Aree sistemate a verde', 'Province_Indicatore prestazione criterio C.6.8': 'Province_Indicatore prestazione criterio C.6.8', });
lyr_Province_ClasseenergeticaA4nzeb_4.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Province_Conteggio certificazioni': 'Province_Conteggio certificazioni', 'Province_Volume incentivo LR 13/2008 mc': 'Province_Volume incentivo LR 13/2008 mc', 'Province_Volume incentivo LR 14/2009 mc': 'Province_Volume incentivo LR 14/2009 mc', 'Province_Volume incentivo decreto Romani mc': 'Province_Volume incentivo decreto Romani mc', 'Province_Punteggio ITACA': 'Province_Punteggio ITACA', 'Province_Classe energetica A4 nzeb': 'Province_Classe energetica A4 nzeb', 'Province_Classe energetica A4': 'Province_Classe energetica A4', 'Province_Classe energetica A3': 'Province_Classe energetica A3', 'Province_Classe energetica A2': 'Province_Classe energetica A2', 'Province_Classe energetica A1': 'Province_Classe energetica A1', 'Province_Classe energetica B': 'Province_Classe energetica B', 'Province_Classe energetica C': 'Province_Classe energetica C', 'Province_Classe energetica D': 'Province_Classe energetica D', 'Province_Emissioni CO2': 'Province_Emissioni CO2', 'Province_CO2 x SU': 'Province_CO2 x SU', 'Province_Impianto FV KW': 'Province_Impianto FV KW', 'Province_% copertura consumi ACS': 'Province_% copertura consumi ACS', 'Province_% consumi ACS, risc, raffr': 'Province_% consumi ACS, risc, raffr', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Province_Indicatore prestazione criterio C.4.3 (%)', 'Province_Aree sistemate a verde': 'Province_Aree sistemate a verde', 'Province_Indicatore prestazione criterio C.6.8': 'Province_Indicatore prestazione criterio C.6.8', });
lyr_Province_PunteggioITACA_5.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Province_Conteggio certificazioni': 'Province_Conteggio certificazioni', 'Province_Volume incentivo LR 13/2008 mc': 'Province_Volume incentivo LR 13/2008 mc', 'Province_Volume incentivo LR 14/2009 mc': 'Province_Volume incentivo LR 14/2009 mc', 'Province_Volume incentivo decreto Romani mc': 'Province_Volume incentivo decreto Romani mc', 'Province_Punteggio ITACA': 'Province_Punteggio ITACA', 'Province_Classe energetica A4 nzeb': 'Province_Classe energetica A4 nzeb', 'Province_Classe energetica A4': 'Province_Classe energetica A4', 'Province_Classe energetica A3': 'Province_Classe energetica A3', 'Province_Classe energetica A2': 'Province_Classe energetica A2', 'Province_Classe energetica A1': 'Province_Classe energetica A1', 'Province_Classe energetica B': 'Province_Classe energetica B', 'Province_Classe energetica C': 'Province_Classe energetica C', 'Province_Classe energetica D': 'Province_Classe energetica D', 'Province_Emissioni CO2': 'Province_Emissioni CO2', 'Province_CO2 x SU': 'Province_CO2 x SU', 'Province_Impianto FV KW': 'Province_Impianto FV KW', 'Province_% copertura consumi ACS': 'Province_% copertura consumi ACS', 'Province_% consumi ACS, risc, raffr': 'Province_% consumi ACS, risc, raffr', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Province_Indicatore prestazione criterio C.4.3 (%)', 'Province_Aree sistemate a verde': 'Province_Aree sistemate a verde', 'Province_Indicatore prestazione criterio C.6.8': 'Province_Indicatore prestazione criterio C.6.8', });
lyr_Province_VolumeincentivodecretoRomanimc_6.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Province_Conteggio certificazioni': 'Province_Conteggio certificazioni', 'Province_Volume incentivo LR 13/2008 mc': 'Province_Volume incentivo LR 13/2008 mc', 'Province_Volume incentivo LR 14/2009 mc': 'Province_Volume incentivo LR 14/2009 mc', 'Province_Volume incentivo decreto Romani mc': 'Province_Volume incentivo decreto Romani mc', 'Province_Punteggio ITACA': 'Province_Punteggio ITACA', 'Province_Classe energetica A4 nzeb': 'Province_Classe energetica A4 nzeb', 'Province_Classe energetica A4': 'Province_Classe energetica A4', 'Province_Classe energetica A3': 'Province_Classe energetica A3', 'Province_Classe energetica A2': 'Province_Classe energetica A2', 'Province_Classe energetica A1': 'Province_Classe energetica A1', 'Province_Classe energetica B': 'Province_Classe energetica B', 'Province_Classe energetica C': 'Province_Classe energetica C', 'Province_Classe energetica D': 'Province_Classe energetica D', 'Province_Emissioni CO2': 'Province_Emissioni CO2', 'Province_CO2 x SU': 'Province_CO2 x SU', 'Province_Impianto FV KW': 'Province_Impianto FV KW', 'Province_% copertura consumi ACS': 'Province_% copertura consumi ACS', 'Province_% consumi ACS, risc, raffr': 'Province_% consumi ACS, risc, raffr', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Province_Indicatore prestazione criterio C.4.3 (%)', 'Province_Aree sistemate a verde': 'Province_Aree sistemate a verde', 'Province_Indicatore prestazione criterio C.6.8': 'Province_Indicatore prestazione criterio C.6.8', });
lyr_Province_VolumeincentivoLR142009mc_7.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Province_Conteggio certificazioni': 'Province_Conteggio certificazioni', 'Province_Volume incentivo LR 13/2008 mc': 'Province_Volume incentivo LR 13/2008 mc', 'Province_Volume incentivo LR 14/2009 mc': 'Province_Volume incentivo LR 14/2009 mc', 'Province_Volume incentivo decreto Romani mc': 'Province_Volume incentivo decreto Romani mc', 'Province_Punteggio ITACA': 'Province_Punteggio ITACA', 'Province_Classe energetica A4 nzeb': 'Province_Classe energetica A4 nzeb', 'Province_Classe energetica A4': 'Province_Classe energetica A4', 'Province_Classe energetica A3': 'Province_Classe energetica A3', 'Province_Classe energetica A2': 'Province_Classe energetica A2', 'Province_Classe energetica A1': 'Province_Classe energetica A1', 'Province_Classe energetica B': 'Province_Classe energetica B', 'Province_Classe energetica C': 'Province_Classe energetica C', 'Province_Classe energetica D': 'Province_Classe energetica D', 'Province_Emissioni CO2': 'Province_Emissioni CO2', 'Province_CO2 x SU': 'Province_CO2 x SU', 'Province_Impianto FV KW': 'Province_Impianto FV KW', 'Province_% copertura consumi ACS': 'Province_% copertura consumi ACS', 'Province_% consumi ACS, risc, raffr': 'Province_% consumi ACS, risc, raffr', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Province_Indicatore prestazione criterio C.4.3 (%)', 'Province_Aree sistemate a verde': 'Province_Aree sistemate a verde', 'Province_Indicatore prestazione criterio C.6.8': 'Province_Indicatore prestazione criterio C.6.8', });
lyr_Province_VolumeincentivoLR132008mc_8.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Province_Conteggio certificazioni': 'Province_Conteggio certificazioni', 'Province_Volume incentivo LR 13/2008 mc': 'Province_Volume incentivo LR 13/2008 mc', 'Province_Volume incentivo LR 14/2009 mc': 'Province_Volume incentivo LR 14/2009 mc', 'Province_Volume incentivo decreto Romani mc': 'Province_Volume incentivo decreto Romani mc', 'Province_Punteggio ITACA': 'Province_Punteggio ITACA', 'Province_Classe energetica A4 nzeb': 'Province_Classe energetica A4 nzeb', 'Province_Classe energetica A4': 'Province_Classe energetica A4', 'Province_Classe energetica A3': 'Province_Classe energetica A3', 'Province_Classe energetica A2': 'Province_Classe energetica A2', 'Province_Classe energetica A1': 'Province_Classe energetica A1', 'Province_Classe energetica B': 'Province_Classe energetica B', 'Province_Classe energetica C': 'Province_Classe energetica C', 'Province_Classe energetica D': 'Province_Classe energetica D', 'Province_Emissioni CO2': 'Province_Emissioni CO2', 'Province_CO2 x SU': 'Province_CO2 x SU', 'Province_Impianto FV KW': 'Province_Impianto FV KW', 'Province_% copertura consumi ACS': 'Province_% copertura consumi ACS', 'Province_% consumi ACS, risc, raffr': 'Province_% consumi ACS, risc, raffr', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Province_Indicatore prestazione criterio C.4.3 (%)', 'Province_Aree sistemate a verde': 'Province_Aree sistemate a verde', 'Province_Indicatore prestazione criterio C.6.8': 'Province_Indicatore prestazione criterio C.6.8', });
lyr_Numerocertificazioniperprovincia_9.set('fieldAliases', {'COD_PRO': 'COD_PRO', 'SIGLA_PR': 'SIGLA_PR', 'NOME_PRO': 'NOME_PRO', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', 'Province_Conteggio certificazioni': 'Province_Conteggio certificazioni', 'Province_Volume incentivo LR 13/2008 mc': 'Province_Volume incentivo LR 13/2008 mc', 'Province_Volume incentivo LR 14/2009 mc': 'Province_Volume incentivo LR 14/2009 mc', 'Province_Volume incentivo decreto Romani mc': 'Province_Volume incentivo decreto Romani mc', 'Province_Punteggio ITACA': 'Province_Punteggio ITACA', 'Province_Classe energetica A4 nzeb': 'Province_Classe energetica A4 nzeb', 'Province_Classe energetica A4': 'Province_Classe energetica A4', 'Province_Classe energetica A3': 'Province_Classe energetica A3', 'Province_Classe energetica A2': 'Province_Classe energetica A2', 'Province_Classe energetica A1': 'Province_Classe energetica A1', 'Province_Classe energetica B': 'Province_Classe energetica B', 'Province_Classe energetica C': 'Province_Classe energetica C', 'Province_Classe energetica D': 'Province_Classe energetica D', 'Province_Emissioni CO2': 'Province_Emissioni CO2', 'Province_CO2 x SU': 'Province_CO2 x SU', 'Province_Impianto FV KW': 'Province_Impianto FV KW', 'Province_% copertura consumi ACS': 'Province_% copertura consumi ACS', 'Province_% consumi ACS, risc, raffr': 'Province_% consumi ACS, risc, raffr', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Province_Indicatore prestazione criterio C.4.3 (%)', 'Province_Aree sistemate a verde': 'Province_Aree sistemate a verde', 'Province_Indicatore prestazione criterio C.6.8': 'Province_Indicatore prestazione criterio C.6.8', });
lyr_Certificatidisostenibilit2022punteggioItaca_10.set('fieldAliases', {'Progressivo': 'Progressivo', 'Data Certificato': 'Data Certificato', 'Nuova costruzione incentivo LR 13/2008': 'Nuova costruzione incentivo LR 13/2008', 'Nuova costruzione incentivo LR 14/2009': 'Nuova costruzione incentivo LR 14/2009', 'Nuova costruzione Decreto Romani': 'Nuova costruzione Decreto Romani', 'Ristr incentivo LR 13/2008': 'Ristr incentivo LR 13/2008', 'Ampliam. incentivo LR 14/2009': 'Ampliam. incentivo LR 14/2009', 'Località': 'Località', 'PR': 'PR', 'Latitudine': 'Latitudine', 'Longitudine': 'Longitudine', 'Volume incentivo  %': 'Volume incentivo  %', 'Volume incentivo LR 13/2008 mc': 'Volume incentivo LR 13/2008 mc', 'Volume incentivo LR 14/2009 mc': 'Volume incentivo LR 14/2009 mc', 'Volume incentivo decreto Romani mc': 'Volume incentivo decreto Romani mc', 'Punteggio ITACA': 'Punteggio ITACA', 'Classe energetica': 'Classe energetica', 'Codice CatastaLE Comune': 'Codice CatastaLE Comune', 'Tipologia residenziaLE': 'Tipologia residenziaLE', 'Tipologia non  residenziaLE': 'Tipologia non  residenziaLE', 'VALORI INDICATORI PRESTAZIONI RELATIVE             A': 'VALORI INDICATORI PRESTAZIONI RELATIVE             A', 'VALORI INDICATORI PRESTAZIONI RELATIVE             B': 'VALORI INDICATORI PRESTAZIONI RELATIVE             B', 'VALORI INDICATORI PRESTAZIONI RELATIVE             C': 'VALORI INDICATORI PRESTAZIONI RELATIVE             C', 'VALORI INDICATORI PRESTAZIONI RELATIVE             D': 'VALORI INDICATORI PRESTAZIONI RELATIVE             D', 'VALORI INDICATORI PRESTAZIONI RELATIVE             E': 'VALORI INDICATORI PRESTAZIONI RELATIVE             E', 'Emissioni CO2': 'Emissioni CO2', 'Superficie utile di intervento (mq)': 'Superficie utile di intervento (mq)', 'CO2 x SU': 'CO2 x SU', 'Impianto FV KW': 'Impianto FV KW', '% copertura consumi ACS': '% copertura consumi ACS', '% consumi ACS, risc, raffr': '% consumi ACS, risc, raffr', 'Indicatore prestazione criterio C.4.3 (%)': 'Indicatore prestazione criterio C.4.3 (%)', 'Aree sistemate a verde': 'Aree sistemate a verde', 'Indicatore prestazione criterio C.6.8': 'Indicatore prestazione criterio C.6.8', });
lyr_Certificatidisostenibilit2022_11.set('fieldAliases', {'Progressivo': 'Progressivo', 'Data Certificato': 'Data Certificato', 'Nuova costruzione incentivo LR 13/2008': 'Nuova costruzione incentivo LR 13/2008', 'Nuova costruzione incentivo LR 14/2009': 'Nuova costruzione incentivo LR 14/2009', 'Nuova costruzione Decreto Romani': 'Nuova costruzione Decreto Romani', 'Ristr incentivo LR 13/2008': 'Ristr incentivo LR 13/2008', 'Ampliam. incentivo LR 14/2009': 'Ampliam. incentivo LR 14/2009', 'Località': 'Località', 'PR': 'PR', 'Latitudine': 'Latitudine', 'Longitudine': 'Longitudine', 'Volume incentivo  %': 'Volume incentivo  %', 'Volume incentivo LR 13/2008 mc': 'Volume incentivo LR 13/2008 mc', 'Volume incentivo LR 14/2009 mc': 'Volume incentivo LR 14/2009 mc', 'Volume incentivo decreto Romani mc': 'Volume incentivo decreto Romani mc', 'Punteggio ITACA': 'Punteggio ITACA', 'Classe energetica': 'Classe energetica', 'Codice CatastaLE Comune': 'Codice CatastaLE Comune', 'Tipologia residenziaLE': 'Tipologia residenziaLE', 'Tipologia non  residenziaLE': 'Tipologia non  residenziaLE', 'VALORI INDICATORI PRESTAZIONI RELATIVE             A': 'VALORI INDICATORI PRESTAZIONI RELATIVE             A', 'VALORI INDICATORI PRESTAZIONI RELATIVE             B': 'VALORI INDICATORI PRESTAZIONI RELATIVE             B', 'VALORI INDICATORI PRESTAZIONI RELATIVE             C': 'VALORI INDICATORI PRESTAZIONI RELATIVE             C', 'VALORI INDICATORI PRESTAZIONI RELATIVE             D': 'VALORI INDICATORI PRESTAZIONI RELATIVE             D', 'VALORI INDICATORI PRESTAZIONI RELATIVE             E': 'VALORI INDICATORI PRESTAZIONI RELATIVE             E', 'Emissioni CO2': 'Emissioni CO2', 'Superficie utile di intervento (mq)': 'Superficie utile di intervento (mq)', 'CO2 x SU': 'CO2 x SU', 'Impianto FV KW': 'Impianto FV KW', '% copertura consumi ACS': '% copertura consumi ACS', '% consumi ACS, risc, raffr': '% consumi ACS, risc, raffr', 'Indicatore prestazione criterio C.4.3 (%)': 'Indicatore prestazione criterio C.4.3 (%)', 'Aree sistemate a verde': 'Aree sistemate a verde', 'Indicatore prestazione criterio C.6.8': 'Indicatore prestazione criterio C.6.8', });
lyr_LimitiProvinciali_1.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', });
lyr_Limiticomunali_2.set('fieldImages', {'OBJECTID': 'TextEdit', 'ID': 'TextEdit', 'AREA_': 'TextEdit', 'PERIMETER': 'TextEdit', 'COMUNI_': 'TextEdit', 'COMUNI_ID': 'TextEdit', 'COD_ISTAT': 'TextEdit', 'NOME_COM': 'TextEdit', 'ISTAT': 'TextEdit', 'COD_REG': 'TextEdit', 'COD_PRO': 'TextEdit', 'COD_COM': 'TextEdit', 'NEWFIELD1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', });
lyr_Province_EmissioniCO2_3.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Province_Conteggio certificazioni': 'Range', 'Province_Volume incentivo LR 13/2008 mc': 'TextEdit', 'Province_Volume incentivo LR 14/2009 mc': 'TextEdit', 'Province_Volume incentivo decreto Romani mc': 'TextEdit', 'Province_Punteggio ITACA': 'TextEdit', 'Province_Classe energetica A4 nzeb': 'Range', 'Province_Classe energetica A4': 'Range', 'Province_Classe energetica A3': 'Range', 'Province_Classe energetica A2': 'Range', 'Province_Classe energetica A1': 'Range', 'Province_Classe energetica B': 'Range', 'Province_Classe energetica C': 'Range', 'Province_Classe energetica D': 'Range', 'Province_Emissioni CO2': 'TextEdit', 'Province_CO2 x SU': 'Range', 'Province_Impianto FV KW': 'TextEdit', 'Province_% copertura consumi ACS': 'TextEdit', 'Province_% consumi ACS, risc, raffr': 'TextEdit', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Range', 'Province_Aree sistemate a verde': 'Range', 'Province_Indicatore prestazione criterio C.6.8': 'Range', });
lyr_Province_ClasseenergeticaA4nzeb_4.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Province_Conteggio certificazioni': 'Range', 'Province_Volume incentivo LR 13/2008 mc': 'TextEdit', 'Province_Volume incentivo LR 14/2009 mc': 'TextEdit', 'Province_Volume incentivo decreto Romani mc': 'TextEdit', 'Province_Punteggio ITACA': 'TextEdit', 'Province_Classe energetica A4 nzeb': 'Range', 'Province_Classe energetica A4': 'Range', 'Province_Classe energetica A3': 'Range', 'Province_Classe energetica A2': 'Range', 'Province_Classe energetica A1': 'Range', 'Province_Classe energetica B': 'Range', 'Province_Classe energetica C': 'Range', 'Province_Classe energetica D': 'Range', 'Province_Emissioni CO2': 'TextEdit', 'Province_CO2 x SU': 'Range', 'Province_Impianto FV KW': 'TextEdit', 'Province_% copertura consumi ACS': 'TextEdit', 'Province_% consumi ACS, risc, raffr': 'TextEdit', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Range', 'Province_Aree sistemate a verde': 'Range', 'Province_Indicatore prestazione criterio C.6.8': 'Range', });
lyr_Province_PunteggioITACA_5.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Province_Conteggio certificazioni': 'Range', 'Province_Volume incentivo LR 13/2008 mc': 'TextEdit', 'Province_Volume incentivo LR 14/2009 mc': 'TextEdit', 'Province_Volume incentivo decreto Romani mc': 'TextEdit', 'Province_Punteggio ITACA': 'TextEdit', 'Province_Classe energetica A4 nzeb': 'Range', 'Province_Classe energetica A4': 'Range', 'Province_Classe energetica A3': 'Range', 'Province_Classe energetica A2': 'Range', 'Province_Classe energetica A1': 'Range', 'Province_Classe energetica B': 'Range', 'Province_Classe energetica C': 'Range', 'Province_Classe energetica D': 'Range', 'Province_Emissioni CO2': 'TextEdit', 'Province_CO2 x SU': 'Range', 'Province_Impianto FV KW': 'TextEdit', 'Province_% copertura consumi ACS': 'TextEdit', 'Province_% consumi ACS, risc, raffr': 'TextEdit', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Range', 'Province_Aree sistemate a verde': 'Range', 'Province_Indicatore prestazione criterio C.6.8': 'Range', });
lyr_Province_VolumeincentivodecretoRomanimc_6.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Province_Conteggio certificazioni': 'Range', 'Province_Volume incentivo LR 13/2008 mc': 'TextEdit', 'Province_Volume incentivo LR 14/2009 mc': 'TextEdit', 'Province_Volume incentivo decreto Romani mc': 'TextEdit', 'Province_Punteggio ITACA': 'TextEdit', 'Province_Classe energetica A4 nzeb': 'Range', 'Province_Classe energetica A4': 'Range', 'Province_Classe energetica A3': 'Range', 'Province_Classe energetica A2': 'Range', 'Province_Classe energetica A1': 'Range', 'Province_Classe energetica B': 'Range', 'Province_Classe energetica C': 'Range', 'Province_Classe energetica D': 'Range', 'Province_Emissioni CO2': 'TextEdit', 'Province_CO2 x SU': 'Range', 'Province_Impianto FV KW': 'TextEdit', 'Province_% copertura consumi ACS': 'TextEdit', 'Province_% consumi ACS, risc, raffr': 'TextEdit', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Range', 'Province_Aree sistemate a verde': 'Range', 'Province_Indicatore prestazione criterio C.6.8': 'Range', });
lyr_Province_VolumeincentivoLR142009mc_7.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Province_Conteggio certificazioni': 'Range', 'Province_Volume incentivo LR 13/2008 mc': 'TextEdit', 'Province_Volume incentivo LR 14/2009 mc': 'TextEdit', 'Province_Volume incentivo decreto Romani mc': 'TextEdit', 'Province_Punteggio ITACA': 'TextEdit', 'Province_Classe energetica A4 nzeb': 'Range', 'Province_Classe energetica A4': 'Range', 'Province_Classe energetica A3': 'Range', 'Province_Classe energetica A2': 'Range', 'Province_Classe energetica A1': 'Range', 'Province_Classe energetica B': 'Range', 'Province_Classe energetica C': 'Range', 'Province_Classe energetica D': 'Range', 'Province_Emissioni CO2': 'TextEdit', 'Province_CO2 x SU': 'Range', 'Province_Impianto FV KW': 'TextEdit', 'Province_% copertura consumi ACS': 'TextEdit', 'Province_% consumi ACS, risc, raffr': 'TextEdit', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Range', 'Province_Aree sistemate a verde': 'Range', 'Province_Indicatore prestazione criterio C.6.8': 'Range', });
lyr_Province_VolumeincentivoLR132008mc_8.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Province_Conteggio certificazioni': 'Range', 'Province_Volume incentivo LR 13/2008 mc': 'TextEdit', 'Province_Volume incentivo LR 14/2009 mc': 'TextEdit', 'Province_Volume incentivo decreto Romani mc': 'TextEdit', 'Province_Punteggio ITACA': 'TextEdit', 'Province_Classe energetica A4 nzeb': 'Range', 'Province_Classe energetica A4': 'Range', 'Province_Classe energetica A3': 'Range', 'Province_Classe energetica A2': 'Range', 'Province_Classe energetica A1': 'Range', 'Province_Classe energetica B': 'Range', 'Province_Classe energetica C': 'Range', 'Province_Classe energetica D': 'Range', 'Province_Emissioni CO2': 'TextEdit', 'Province_CO2 x SU': 'Range', 'Province_Impianto FV KW': 'TextEdit', 'Province_% copertura consumi ACS': 'TextEdit', 'Province_% consumi ACS, risc, raffr': 'TextEdit', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Range', 'Province_Aree sistemate a verde': 'Range', 'Province_Indicatore prestazione criterio C.6.8': 'Range', });
lyr_Numerocertificazioniperprovincia_9.set('fieldImages', {'COD_PRO': 'TextEdit', 'SIGLA_PR': 'TextEdit', 'NOME_PRO': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'SHAPE_LEN': 'TextEdit', 'Province_Conteggio certificazioni': 'Range', 'Province_Volume incentivo LR 13/2008 mc': 'TextEdit', 'Province_Volume incentivo LR 14/2009 mc': 'TextEdit', 'Province_Volume incentivo decreto Romani mc': 'TextEdit', 'Province_Punteggio ITACA': 'TextEdit', 'Province_Classe energetica A4 nzeb': 'Range', 'Province_Classe energetica A4': 'Range', 'Province_Classe energetica A3': 'Range', 'Province_Classe energetica A2': 'Range', 'Province_Classe energetica A1': 'Range', 'Province_Classe energetica B': 'Range', 'Province_Classe energetica C': 'Range', 'Province_Classe energetica D': 'Range', 'Province_Emissioni CO2': 'TextEdit', 'Province_CO2 x SU': 'Range', 'Province_Impianto FV KW': 'TextEdit', 'Province_% copertura consumi ACS': 'TextEdit', 'Province_% consumi ACS, risc, raffr': 'TextEdit', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'Range', 'Province_Aree sistemate a verde': 'Range', 'Province_Indicatore prestazione criterio C.6.8': 'Range', });
lyr_Certificatidisostenibilit2022punteggioItaca_10.set('fieldImages', {'Progressivo': 'Range', 'Data Certificato': 'TextEdit', 'Nuova costruzione incentivo LR 13/2008': 'TextEdit', 'Nuova costruzione incentivo LR 14/2009': 'TextEdit', 'Nuova costruzione Decreto Romani': 'TextEdit', 'Ristr incentivo LR 13/2008': 'TextEdit', 'Ampliam. incentivo LR 14/2009': 'Range', 'Località': 'TextEdit', 'PR': 'TextEdit', 'Latitudine': 'TextEdit', 'Longitudine': 'TextEdit', 'Volume incentivo  %': 'TextEdit', 'Volume incentivo LR 13/2008 mc': 'TextEdit', 'Volume incentivo LR 14/2009 mc': 'TextEdit', 'Volume incentivo decreto Romani mc': 'TextEdit', 'Punteggio ITACA': 'TextEdit', 'Classe energetica': 'TextEdit', 'Codice CatastaLE Comune': 'TextEdit', 'Tipologia residenziaLE': 'TextEdit', 'Tipologia non  residenziaLE': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             A': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             B': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             C': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             D': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             E': 'TextEdit', 'Emissioni CO2': 'TextEdit', 'Superficie utile di intervento (mq)': '', 'CO2 x SU': '', 'Impianto FV KW': 'TextEdit', '% copertura consumi ACS': 'TextEdit', '% consumi ACS, risc, raffr': 'TextEdit', 'Indicatore prestazione criterio C.4.3 (%)': '', 'Aree sistemate a verde': '', 'Indicatore prestazione criterio C.6.8': '', });
lyr_Certificatidisostenibilit2022_11.set('fieldImages', {'Progressivo': 'Range', 'Data Certificato': 'TextEdit', 'Nuova costruzione incentivo LR 13/2008': 'TextEdit', 'Nuova costruzione incentivo LR 14/2009': 'TextEdit', 'Nuova costruzione Decreto Romani': 'TextEdit', 'Ristr incentivo LR 13/2008': 'TextEdit', 'Ampliam. incentivo LR 14/2009': 'Range', 'Località': 'TextEdit', 'PR': 'TextEdit', 'Latitudine': 'TextEdit', 'Longitudine': 'TextEdit', 'Volume incentivo  %': 'TextEdit', 'Volume incentivo LR 13/2008 mc': 'TextEdit', 'Volume incentivo LR 14/2009 mc': 'TextEdit', 'Volume incentivo decreto Romani mc': 'TextEdit', 'Punteggio ITACA': 'TextEdit', 'Classe energetica': 'TextEdit', 'Codice CatastaLE Comune': 'TextEdit', 'Tipologia residenziaLE': 'TextEdit', 'Tipologia non  residenziaLE': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             A': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             B': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             C': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             D': 'TextEdit', 'VALORI INDICATORI PRESTAZIONI RELATIVE             E': 'TextEdit', 'Emissioni CO2': 'TextEdit', 'Superficie utile di intervento (mq)': '', 'CO2 x SU': '', 'Impianto FV KW': 'TextEdit', '% copertura consumi ACS': 'TextEdit', '% consumi ACS, risc, raffr': 'TextEdit', 'Indicatore prestazione criterio C.4.3 (%)': '', 'Aree sistemate a verde': '', 'Indicatore prestazione criterio C.6.8': '', });
lyr_LimitiProvinciali_1.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', });
lyr_Limiticomunali_2.set('fieldLabels', {'OBJECTID': 'no label', 'ID': 'no label', 'AREA_': 'no label', 'PERIMETER': 'no label', 'COMUNI_': 'no label', 'COMUNI_ID': 'no label', 'COD_ISTAT': 'no label', 'NOME_COM': 'no label', 'ISTAT': 'no label', 'COD_REG': 'no label', 'COD_PRO': 'no label', 'COD_COM': 'no label', 'NEWFIELD1': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', });
lyr_Province_EmissioniCO2_3.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', 'Province_Conteggio certificazioni': 'no label', 'Province_Volume incentivo LR 13/2008 mc': 'no label', 'Province_Volume incentivo LR 14/2009 mc': 'no label', 'Province_Volume incentivo decreto Romani mc': 'no label', 'Province_Punteggio ITACA': 'no label', 'Province_Classe energetica A4 nzeb': 'no label', 'Province_Classe energetica A4': 'no label', 'Province_Classe energetica A3': 'no label', 'Province_Classe energetica A2': 'no label', 'Province_Classe energetica A1': 'no label', 'Province_Classe energetica B': 'no label', 'Province_Classe energetica C': 'no label', 'Province_Classe energetica D': 'no label', 'Province_Emissioni CO2': 'no label', 'Province_CO2 x SU': 'no label', 'Province_Impianto FV KW': 'no label', 'Province_% copertura consumi ACS': 'no label', 'Province_% consumi ACS, risc, raffr': 'no label', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Province_Aree sistemate a verde': 'no label', 'Province_Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Province_ClasseenergeticaA4nzeb_4.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', 'Province_Conteggio certificazioni': 'no label', 'Province_Volume incentivo LR 13/2008 mc': 'no label', 'Province_Volume incentivo LR 14/2009 mc': 'no label', 'Province_Volume incentivo decreto Romani mc': 'no label', 'Province_Punteggio ITACA': 'no label', 'Province_Classe energetica A4 nzeb': 'no label', 'Province_Classe energetica A4': 'no label', 'Province_Classe energetica A3': 'no label', 'Province_Classe energetica A2': 'no label', 'Province_Classe energetica A1': 'no label', 'Province_Classe energetica B': 'no label', 'Province_Classe energetica C': 'no label', 'Province_Classe energetica D': 'no label', 'Province_Emissioni CO2': 'no label', 'Province_CO2 x SU': 'no label', 'Province_Impianto FV KW': 'no label', 'Province_% copertura consumi ACS': 'no label', 'Province_% consumi ACS, risc, raffr': 'no label', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Province_Aree sistemate a verde': 'no label', 'Province_Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Province_PunteggioITACA_5.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', 'Province_Conteggio certificazioni': 'no label', 'Province_Volume incentivo LR 13/2008 mc': 'no label', 'Province_Volume incentivo LR 14/2009 mc': 'no label', 'Province_Volume incentivo decreto Romani mc': 'no label', 'Province_Punteggio ITACA': 'no label', 'Province_Classe energetica A4 nzeb': 'no label', 'Province_Classe energetica A4': 'no label', 'Province_Classe energetica A3': 'no label', 'Province_Classe energetica A2': 'no label', 'Province_Classe energetica A1': 'no label', 'Province_Classe energetica B': 'no label', 'Province_Classe energetica C': 'no label', 'Province_Classe energetica D': 'no label', 'Province_Emissioni CO2': 'no label', 'Province_CO2 x SU': 'no label', 'Province_Impianto FV KW': 'no label', 'Province_% copertura consumi ACS': 'no label', 'Province_% consumi ACS, risc, raffr': 'no label', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Province_Aree sistemate a verde': 'no label', 'Province_Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Province_VolumeincentivodecretoRomanimc_6.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'inline label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', 'Province_Conteggio certificazioni': 'no label', 'Province_Volume incentivo LR 13/2008 mc': 'no label', 'Province_Volume incentivo LR 14/2009 mc': 'no label', 'Province_Volume incentivo decreto Romani mc': 'no label', 'Province_Punteggio ITACA': 'no label', 'Province_Classe energetica A4 nzeb': 'no label', 'Province_Classe energetica A4': 'no label', 'Province_Classe energetica A3': 'no label', 'Province_Classe energetica A2': 'no label', 'Province_Classe energetica A1': 'no label', 'Province_Classe energetica B': 'no label', 'Province_Classe energetica C': 'no label', 'Province_Classe energetica D': 'no label', 'Province_Emissioni CO2': 'no label', 'Province_CO2 x SU': 'no label', 'Province_Impianto FV KW': 'no label', 'Province_% copertura consumi ACS': 'no label', 'Province_% consumi ACS, risc, raffr': 'no label', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Province_Aree sistemate a verde': 'no label', 'Province_Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Province_VolumeincentivoLR142009mc_7.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', 'Province_Conteggio certificazioni': 'no label', 'Province_Volume incentivo LR 13/2008 mc': 'no label', 'Province_Volume incentivo LR 14/2009 mc': 'no label', 'Province_Volume incentivo decreto Romani mc': 'no label', 'Province_Punteggio ITACA': 'no label', 'Province_Classe energetica A4 nzeb': 'no label', 'Province_Classe energetica A4': 'no label', 'Province_Classe energetica A3': 'no label', 'Province_Classe energetica A2': 'no label', 'Province_Classe energetica A1': 'no label', 'Province_Classe energetica B': 'no label', 'Province_Classe energetica C': 'no label', 'Province_Classe energetica D': 'no label', 'Province_Emissioni CO2': 'no label', 'Province_CO2 x SU': 'no label', 'Province_Impianto FV KW': 'no label', 'Province_% copertura consumi ACS': 'no label', 'Province_% consumi ACS, risc, raffr': 'no label', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Province_Aree sistemate a verde': 'no label', 'Province_Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Province_VolumeincentivoLR132008mc_8.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', 'Province_Conteggio certificazioni': 'no label', 'Province_Volume incentivo LR 13/2008 mc': 'no label', 'Province_Volume incentivo LR 14/2009 mc': 'no label', 'Province_Volume incentivo decreto Romani mc': 'no label', 'Province_Punteggio ITACA': 'no label', 'Province_Classe energetica A4 nzeb': 'no label', 'Province_Classe energetica A4': 'no label', 'Province_Classe energetica A3': 'no label', 'Province_Classe energetica A2': 'no label', 'Province_Classe energetica A1': 'no label', 'Province_Classe energetica B': 'no label', 'Province_Classe energetica C': 'no label', 'Province_Classe energetica D': 'no label', 'Province_Emissioni CO2': 'no label', 'Province_CO2 x SU': 'no label', 'Province_Impianto FV KW': 'no label', 'Province_% copertura consumi ACS': 'no label', 'Province_% consumi ACS, risc, raffr': 'no label', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Province_Aree sistemate a verde': 'no label', 'Province_Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Numerocertificazioniperprovincia_9.set('fieldLabels', {'COD_PRO': 'no label', 'SIGLA_PR': 'no label', 'NOME_PRO': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', 'Province_Conteggio certificazioni': 'no label', 'Province_Volume incentivo LR 13/2008 mc': 'no label', 'Province_Volume incentivo LR 14/2009 mc': 'no label', 'Province_Volume incentivo decreto Romani mc': 'no label', 'Province_Punteggio ITACA': 'no label', 'Province_Classe energetica A4 nzeb': 'no label', 'Province_Classe energetica A4': 'no label', 'Province_Classe energetica A3': 'no label', 'Province_Classe energetica A2': 'no label', 'Province_Classe energetica A1': 'no label', 'Province_Classe energetica B': 'no label', 'Province_Classe energetica C': 'no label', 'Province_Classe energetica D': 'no label', 'Province_Emissioni CO2': 'no label', 'Province_CO2 x SU': 'no label', 'Province_Impianto FV KW': 'no label', 'Province_% copertura consumi ACS': 'no label', 'Province_% consumi ACS, risc, raffr': 'no label', 'Province_Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Province_Aree sistemate a verde': 'no label', 'Province_Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Certificatidisostenibilit2022punteggioItaca_10.set('fieldLabels', {'Progressivo': 'no label', 'Data Certificato': 'no label', 'Nuova costruzione incentivo LR 13/2008': 'no label', 'Nuova costruzione incentivo LR 14/2009': 'no label', 'Nuova costruzione Decreto Romani': 'no label', 'Ristr incentivo LR 13/2008': 'no label', 'Ampliam. incentivo LR 14/2009': 'no label', 'Località': 'no label', 'PR': 'no label', 'Latitudine': 'no label', 'Longitudine': 'no label', 'Volume incentivo  %': 'no label', 'Volume incentivo LR 13/2008 mc': 'no label', 'Volume incentivo LR 14/2009 mc': 'no label', 'Volume incentivo decreto Romani mc': 'no label', 'Punteggio ITACA': 'no label', 'Classe energetica': 'no label', 'Codice CatastaLE Comune': 'no label', 'Tipologia residenziaLE': 'no label', 'Tipologia non  residenziaLE': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             A': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             B': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             C': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             D': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             E': 'no label', 'Emissioni CO2': 'no label', 'Superficie utile di intervento (mq)': 'no label', 'CO2 x SU': 'no label', 'Impianto FV KW': 'no label', '% copertura consumi ACS': 'no label', '% consumi ACS, risc, raffr': 'no label', 'Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Aree sistemate a verde': 'no label', 'Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Certificatidisostenibilit2022_11.set('fieldLabels', {'Progressivo': 'no label', 'Data Certificato': 'no label', 'Nuova costruzione incentivo LR 13/2008': 'no label', 'Nuova costruzione incentivo LR 14/2009': 'no label', 'Nuova costruzione Decreto Romani': 'no label', 'Ristr incentivo LR 13/2008': 'no label', 'Ampliam. incentivo LR 14/2009': 'no label', 'Località': 'no label', 'PR': 'no label', 'Latitudine': 'no label', 'Longitudine': 'no label', 'Volume incentivo  %': 'no label', 'Volume incentivo LR 13/2008 mc': 'no label', 'Volume incentivo LR 14/2009 mc': 'no label', 'Volume incentivo decreto Romani mc': 'no label', 'Punteggio ITACA': 'no label', 'Classe energetica': 'no label', 'Codice CatastaLE Comune': 'no label', 'Tipologia residenziaLE': 'no label', 'Tipologia non  residenziaLE': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             A': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             B': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             C': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             D': 'no label', 'VALORI INDICATORI PRESTAZIONI RELATIVE             E': 'no label', 'Emissioni CO2': 'no label', 'Superficie utile di intervento (mq)': 'no label', 'CO2 x SU': 'no label', 'Impianto FV KW': 'no label', '% copertura consumi ACS': 'no label', '% consumi ACS, risc, raffr': 'no label', 'Indicatore prestazione criterio C.4.3 (%)': 'no label', 'Aree sistemate a verde': 'no label', 'Indicatore prestazione criterio C.6.8': 'no label', });
lyr_Certificatidisostenibilit2022_11.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});